language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

branches:
  except:
    - /^dev[-_]/

before_install:
  - mysql --execute="CREATE DATABASE robert;" --user=root
  # GITHUB_OAUTH_TOKEN doit être défini comme une variable d'environnement (dans les paramètres sur le site de Travis CI) contenant un jeton d'accès généré par GitHub
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

before_script:
  - composer install --no-interaction --no-progress

script: phpunit --configuration test/phpunit-travis-ci.xml --test-suffix Test.class.php .
