
language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS robert;" -u root

before_script:
  - composer install

script: phpunit --configuration test/phpunit-travis-ci.xml --test-suffix Test.class.php .
